site_name: Ferma
theme: material
repo_name: 'Syncleus/Ferma'
repo_url: 'https://github.com/Syncleus/Ferma'
site_dir: 'target/mkdocs'
edit_uri: 'edit/master/docs'
site_description: 'An ORM / OGM for the TinkerPop graph stack.'
site_author: 'Syncleus'
copyright: 'Copyright &copy; 2004 - 2018 Syncleus, Inc.'
site_url: 'http://syncleus.com/Ferma'
pages:
    - Home: index.md
    - Getting Started: getting_started.md
    - Features: features.md
    - Object Mapping: object_mapping.md
    - Core Annotations:
        - Overview: annotations/overview.md
        - '@Adjacency': annotations/adjacency.md
        - '@GraphElement': annotations/graphelement.md
        - '@Incidence': annotations/incidence.md
        - '@InVertex': annotations/invertex.md
        - '@OutVertex': annotations/outvertex.md
        - '@Property': annotations/property.md
    - Comparing the Alternatives: comparing_the_alternatives.md
    - Glossary: glossary.md
extra:
  version: '3.3.0'
  logo: 'images/ferma-logo.svg'
  github:
    download_release: true
  palette:
    primary: 'blue'
    accent: 'deep orange'
  author:
    github: 'Syncleus'
  social:
    - type: 'github'
      link: 'https://github.com/Syncleus'
  disqus: 'syncleus'

markdown_extensions:
  - codehilite
  - admonition
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
